exclude: /migrations/|/data/
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
        language_version: python3.13

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix, "--preview", "--show-source"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'uv run mypy app'
        language: system
        types: [python]
        pass_filenames: false
