[project]
name = "waseem-django-template"
version = "0.1.0"
description = ""
authors = [{ name = "Waseem akram", email = "waseem07799@gmail.com" }]
requires-python = "==3.13.1"
readme = "README.md"
dependencies = [
    "cookiecutter>=2.1.1,<3",
    "jinja2-git>=1.3.0,<2",
    "pre-commit>=3.2.2,<4",
    "black>=23.3.0,<24",
    "flake8>=6.0.0,<7",
    "mypy>=1.2.0,<2",
    "pylint>=2.17.2,<3",
    "pylint-django>=2.5.3,<3",
]


[tool.uv]
dev-dependencies = ["djlint>=1.32.1,<2"]

[tool.hatch.build.targets.sdist]
include = ["waseem_django_template"]

[tool.hatch.build.targets.wheel]
include = ["waseem_django_template"]

[tool.pyright]
exclude = [".venv"]
venvPath = "."
venv = ".venv"

[tool.basedpyright]
include = ["app"]
venvPath = "./.venv"
pythonVersion = "3.13.1"
pythonPlatform = "Linux"
typeCheckingMode = "off"

reportMissingTypeStubs = false
reportIncompatibleVariableOverride = false
reportUnusedParameter = false

[tool.djlint]
custom_html = "mjml,mj-head,mj-\\w+"

[tool.mypy]

# https://mypy.readthedocs.io/en/stable/config_file.html

python_version = "3.13.1"
mypy_path = "."


plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

exclude = ['manage.py']

disable_error_code = ['import-untyped']


allow_redefinition = false
check_untyped_defs = true
disallow_any_explicit = false
disallow_any_generics = true
disallow_any_unimported = false
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
error_summary = true
# explicit_package_bases = true
ignore_errors = false
ignore_missing_imports = false
implicit_reexport = false
local_partial_types = true
no_implicit_optional = true
pretty = true
show_error_codes = true
show_error_context = true
strict = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.mypy_django_plugin]
ignore_missing_model_attributes = true

[tool.django-stubs]
module = "django-stubs"
django_settings_module = "app.settings"

[[tool.mypy.overrides]]
module = "*.migrations.*"
# Django migrations should not produce any errors:
ignore_errors = true

[tool.ruff]

exclude = [
    "*.egg",
    "*/migrations/*.py",
    ".bzr",
    ".cache",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".local",
    ".mypy_cache",
    ".nox",
    ".npm",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pycache__",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "manage.py",
    "node_modules",
    "site-packages",
    "venv",
]

extend-select = [
    "A", # flake8-builtins
    # flake8-annotations - https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN205",
    "ANN206",
    "ARG",    # flake8-unused-arguments (ARG)
    "ASYNC",  # flake8-async (ASYNC)
    "B",      # flake8-bugbear
    "BLE",    # flake8-blind-except
    "C4",     # flake8-comprehensions (C4)
    "C90",    # mccabe (C90)
    "DJ",     # flake8-django
    "DTZ",    # flake8-datetimez (DTZ)
    "E",      # pycodestyle Error
    "ERA",    # eradicate (ERA)
    "F",      # Pyflakes
    "FBT",    # flake8-boolean-trap (FBT)
    "FIX",    # flake8-fixme (FIX)
    "FURB",   # refurb (FURB)
    "G",      # flake8-logging-format
    "I",      # isort
    "ICN",    # flake8-import-conventions
    "LOG",    # flake8-logging (LOG)
    "N",      # pep8-naming
    "PERF",   # Perflint (PERF)
    "PIE",    # flake8-pie
    "PTH",    # flake8-use-pathlib (PTH)
    "PYI",    # flake8-pyi
    "Q",      # flake8-quotes
    "RET",    # flake8-return (RET)
    "RSE",    # flake8-raise (RSE)
    "RUF",    # Ruff-specific rules (RUF)
    "SIM",    # flake8-simplify
    "SLF",    # flake8-self (SLF)
    "T10",    # flake8-debugger (T10)
    "T20",    # flake8-print
    # "TD",    # flake8-todos (TD)
    "TID", # flake8-tidy-imports (TID)
    "TRY", # tryceratops (TRY)
    "W",   # pycodestyle Warning
    # "D",     # pydocstyle (D)
    "FLY",  # flynt (FLY)
    "SLOT", #flake8-slots
]
ignore = [
    "D100", # undocumented-public-module
    "D104", # undocumented-public-package
    # "D203",   # one-blank-line-before-class
    "D212",   # multi-line-summary-first-line
    "RUF012", # mutable-class-default
    "TRY003", # raise-vanilla-args
    'A003',   # builtin-attribute-shadowing
]

line-length = 79
indent-width = 4

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# select = ["E4", "E7", "E9", "F"]
# ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.lint.per-file-ignores]
"**/admin/*" = [
    "RUF012", # mutable-class-default
    "D101",   # undocumented-public-class
]
"**/__init__.py" = [
    "F403", # undefined-local-with-import-star
    "F401", # unused-import
]
"**/{tests,docs,tools}/*" = ["E402", "E501"]

"**/management/commands/*" = [
    'A003', # builtin-attribute-shadowing
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings"
filterwarnings = ["ignore::DeprecationWarning"]


addopts = [
    '--create-db',
    '--color=yes',
    '--strict-markers',
    '--strict-config',
    '--tb=short',
    # '--durations=0',
    # '--durations-min=0.5',
    '--cov=app/',
    '--cov-report=html',
    # '--doctest-modules',
    # '--cov-report=term',
]

markers = [
    "unit: mark as Unit Tests",
    "integration: mark as Integration",
    "e2e: mark as End to End",
    "slow: mark test as slow.",
]

[tool.pytest_env]
TEST = true
LOG_DB = false
DEBUG = false

[tool.coverage.run]
branch = true
disable_warnings = ["no-data-collected"]
omit = [
    './app/settings/*',
    './app/tests/*',
    './app/migrations/*',
    './app/celery.py',
    './app/celeryconfig.py',
    './app/schema.py',
    './app/wsgi.py',
    './app/asgi.py',
]

[tool.coverage.report]
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",
    "if TYPE_CHECKING",
    "if DEBUG",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",

    # Skip any pass lines such as may be used for @abstractmethod
    "pass",

    # Have to re-enable the standard pragma
    "pragma: no cover",
]
