services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/{{ cookiecutter.project_slug }}:cached
    working_dir: /workspaces/{{ cookiecutter.project_slug }}
    environment:
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis:6379/0
{% if cookiecutter.enable_celery == "yes" %}
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
{% endif %}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
