FROM python:3.11-slim-buster

ARG APP_HOME=/app
ARG BUILD_ENVIRONMENT=production
ARG UID=1000
ARG GID=1000

ENV DJANGO_ENV ${BUILD_ENVIRONMENT}
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE=1
ENV POETRY_VERSION=1.2.2
ENV POETRY_NO_INTERACTION=1
ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_CACHE_DIR='/var/cache/pypoetry'
ENV POETRY_HOME='/usr/local'

WORKDIR ${APP_HOME}

RUN groupadd -g "${GID}" -r web \
  && useradd -d $APP_HOME -g web -l -r -u "${UID}" web \
  && chown web:web -R $APP_HOME \
  # Static files:
  && mkdir -p '/var/www/static' \
  && chown -R web:web '/var/www/static'



RUN apt-get update && apt-get install --no-install-recommends -y \
  # dependencies for building Python packages
  build-essential \
  # psycopg2 dependencies
  libpq-dev \
  # Other tools \
  curl bash \
  # Cleaning cache:
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN curl -sSL 'https://install.python-poetry.org' | POETRY_HOME='/usr/local' python - \
  && poetry --version

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install --no-install-recommends -y nodejs \
    && npm install -g npm@9.1.2


COPY --chown=web:web ./poetry.lock ./pyproject.toml ${APP_HOME}/

RUN cd ${APP_HOME} && poetry config virtualenvs.create false \
  && poetry install --without local --no-interaction --no-ansi


COPY --chown=web:web . ${APP_HOME}/

COPY --chown=web:web ./compose/production/app/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY --chown=web:web ./compose/production/app/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

RUN chown -R web:web ${APP_HOME}

USER web

ENTRYPOINT ["/entrypoint"]
