#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# NOTE this command will fail if django-compressor is disabled
#python /app/manage.py compress

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:3000 --chdir=/app
