version: "3.8"

volumes:
  {{cookiecutter.project_name}}_postgres_data: { }



services:

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    environment:
      TZ: Asia/Kolkata
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:7
    container_name: {{cookiecutter.project_name}}_redis
    ports:
      - "6379:6379"

  postgres_17:
    image: postgres:17
    container_name: {{cookiecutter.project_name}}_postgres
    volumes:
      - {{cookiecutter.project_name}}_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"