version: "3.8"

volumes:
  {{cookiecutter.project_name}}_local_postgres_data: { }



services:

  mailpit:
    image: axllent/mailpit
    container_name: {{cookiecutter.project_name}}_local_mailpit
    environment:
      TZ: Asia/Kolkata
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:6.2-alpine
    container_name: {{cookiecutter.project_name}}_local_redis
    ports:
      - "6379:6379"

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
          POSTGRES_VERSION: 15
    container_name: {{cookiecutter.project_name}}_local_postgres
    volumes:
      - {{cookiecutter.project_name}}_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
