{% raw %}
dev:
  poetry run python manage.py runserver_plus 0.0.0.0:8000

vite:
  npm run dev

lint:
  poetry run pre-commit run --all-files

type:
  poetry run mypy server

celery:
  poetry run watchmedo auto-restart --directory=server --recursive --pattern '*.py' -- -- celery --app server worker -E -l INFO -Q celery --pool gevent --concurrency 20

makemigrations:
  poetry run python manage.py makemigrations

migrate:
  poetry run python manage.py migrate

dbshell:
  poetry run python manage.py dbshell

notebook:
  DJANGO_ALLOW_ASYNC_UNSAFE=true poetry run python manage.py shell_plus --notebook --no-browser

shell:
  poetry run python manage.py shell_plus

up:
  docker-compose -f development.yml up -d

stop:
  docker-compose -f development.yml stop

down:
  docker-compose -f development.yml down

docker-shell CONTAINER_NAME:
  docker-compose -f development.yml exec {{ CONTAINER_NAME }} bash

{% endraw %}
