version: '3.8'

services:
    caddy:
        restart: unless-stopped
        image: caddy:2.7
        # image: caddy
        # build:
        #     context: .
        #     dockerfile: docker/caddy/Dockerfile
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile # configuration
            - caddy-config:/config # configuration autosaves
            - caddy-data:/data # saving certificates
            - /data/static:/var/www/static:ro # serving django's statics
            - /data/log:/var/log:rw
        env_file:
            - .env
        ports:
            - '80:80/tcp'
            - '80:80/udp'
            - '443:443/tcp'
            - '443:443/udp'
        depends_on:
            - web
        networks:
            - proxynet

    web: &web
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                POSTGRES_VERSION: 15
        image: production_web_server
        command: gunicorn
        volumes:
            - tmp-data:/tmp
            - /data/static:/var/www/static:rw
            - /data/log:/var/log:rw
            - /data:/data:rw
        depends_on:
            - postgres
            - redis
            - mjml
        env_file:
            - .env
        expose:
            - '3000'
        networks:
            - webnet
            - proxynet

    worker_cpu:
      <<: *web
      command: celery
      environment:
        - CELERY_POOL=solo
        - CELERY_CONCURRENCY=1
        - CELERY_QUEUES=celery

    worker_io:
      <<: *web
      command: celery
      environment:
        - CELERY_POOL=gevent
        - CELERY_CONCURRENCY=10
        - CELERY_QUEUES=celery_io

    celery_beat:
      <<: *web
      command: celery-beat

    celery_flower:
      <<: *web
      command: celery-flower
      ports:
        - "5555:5555/tcp"
      networks:
          - webnet

    redis:
        restart: unless-stopped
        image: redis:6.2-alpine
        container_name: redis_production
        volumes:
            - redis-data:/data
        expose:
            - '6379'
        networks:
            - webnet

    postgres:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/postgres/Dockerfile
            args:
                POSTGRES_VERSION: 15
        container_name: web_production_postgres
        volumes:
            - /data/postgresql/data:/var/lib/postgresql/data
            - /data:/data:rw
            - /data/db-backups:/backups
        env_file:
            - .env
        expose:
            - '5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - webnet

    mjml:
        image: liminspace/mjml-tcpserver:0.11
        container_name: mjml_tcpserver_production
        restart: unless-stopped
        environment:
            HOST: '0.0.0.0'
            PORT: '28101'
            MJML_ARGS: '--mjml.minify=true --mjml.validationLevel=strict'
        expose:
            - '28101'
        networks:
            - webnet

    pg_bouncer:
        restart: unless-stopped
        image: edoburu/pgbouncer
        container_name: web_production_pgbouncer
        env_file:
            - .env
        expose:
            - '5432'
        networks:
            - webnet

    awscli:
        build:
            context: .
            dockerfile: docker/aws/Dockerfile
        container_name: aws_cli
        volumes:
            - /data/db-backups:/backups
        env_file:
            - .env

volumes:
    caddy-config:
    caddy-data:
    redis-data:
    tmp-data:

networks:
    webnet:
    proxynet:
