version: "3.8"

services:

  caddy:
    restart: unless-stopped
    image: caddy:2.6.2
    volumes:
      - ./compose/production/caddy/Caddyfile:/etc/caddy/Caddyfile  # configuration
      - caddy-config:/config  # configuration autosaves
      - caddy-data:/data  # saving certificates
      - {{ cookiecutter.project_name }}-static:/var/www/static:ro # serving django's statics
      - /var/log:/var/log:rw
    env_file:
      - env/.production.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - {{ cookiecutter.project_name }}
    networks:
      - proxynet

  {{ cookiecutter.project_name }}:&{{ cookiecutter.project_name }}
    restart: unless-stopped
    build:
      context: .
      dockerfile: compose/production/{{ cookiecutter.project_name }}/Dockerfile
    image: production_{{ cookiecutter.project_name }}_server
    container_name: {{ cookiecutter.project_name }}_production_server
    command: /start
    volumes:
      - {{ cookiecutter.project_name }}-static:/var/www/static:rw
      - /var/log:/var/log:rw
    depends_on:
      - postgres
      - redis
      - mjml
    env_file:
      - env/.production.env
    expose:
      - "3000"
    networks:
      - webnet
      - proxynet

  celery_worker:
    <<: *{{ cookiecutter.project_name }}
    container_name: "celery_worker"
    command: /start-celery-worker


  celery_beat:
    <<: *{{ cookiecutter.project_name }}
    container_name: "celery_beat"
    command: /start-celery-beat


  celery_flower:
    <<: *{{ cookiecutter.project_name }}
    container_name: "celery_flower"
    command: /start-celery-flower

  redis:
    restart: unless-stopped
    image: redis:6.2-alpine
    container_name: redis_production
    expose:
      - "6379"
    networks:
      - webnet

  postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: compose/production/postgres/Dockerfile
    container_name: {{ cookiecutter.project_name }}_production_postgres
    volumes:
      - {{ cookiecutter.project_name }}-postgres-data:/var/lib/postgresql/data
    env_file:
      - env/.production.env
    expose:
      - "5432"
    networks:
      - webnet

  mjml:
    image: liminspace/mjml-tcpserver:0.11
    container_name: mjml_tcpserver_production
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: "28101"
      MJML_ARGS: "--mjml.minify=true --mjml.validationLevel=strict"
    expose:
      - "28101"
    networks:
      - webnet

volumes:
  {{ cookiecutter.project_name }}-static:
  {{ cookiecutter.project_name }}-postgres-data:
  {{ cookiecutter.project_name }}-logs:
  caddy-config:
  caddy-data:

networks:
  webnet:
  proxynet:
