#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

readonly cmd="$*"

: "${DJANGO_DATABASE_HOST:=db}"
: "${DJANGO_DATABASE_PORT:=5432}"

# We need this line to make sure that this container is started
# after the one with postgres:
wait-for-it \
  --host="$DJANGO_DATABASE_HOST" \
  --port="$DJANGO_DATABASE_PORT" \
  --timeout=90 \
  --strict

# It is also possible to wait for other services as well: redis, elastic, mongo
echo "Postgres ${DJANGO_DATABASE_HOST}:${DJANGO_DATABASE_PORT} is up"

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput --clear

# Precompress static files with brotli and gzip.
# The list of ignored file types was taken from https://github.com/evansd/whitenoise
find /var/www/static -type f \
  ! -regex '^.+\.\(jpg\|jpeg\|png\|gif\|webp\|zip\|gz\|tgz\|bz2\|tbz\|xz\|br\|swf\|flv\|woff\|woff2\|3gp\|3gpp\|asf\|avi\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|wmv\)$' \
  -exec brotli --force --best {} \+ \
  -exec gzip --force --keep --best {} \+


# Evaluating passed command (do not touch):
# shellcheck disable=SC2086
exec $cmd
