#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
# python /app/manage.py collectstatic --noinput --clear
python /app/manage.py collectstatic --noinput

# Precompress static files with brotli and gzip.
# The list of ignored file types was taken from https://github.com/evansd/whitenoise
# find /var/www/static -type f \
#   ! -regex '^.+\.\(jpg\|jpeg\|png\|gif\|webp\|zip\|gz\|tgz\|bz2\|tbz\|xz\|br\|swf\|flv\|woff\|woff2\|3gp\|3gpp\|asf\|avi\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|wmv\)$' \
# -exec brotli --force --best {} \+ \
# -exec gzip --force --keep --best {} \+


exec /usr/local/bin/gunicorn ${GUNICORN_APPLICATION} --config /app/compose/production/app/gunicorn_config.py
