"""Django settings for {{cookiecutter.project_verbose_name}}.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _
from env import Env

from app.settings.components.djfk import DJFK_FRONTEND_DIR
from app.settings.vars import BASE_DIR, DEBUG, STATIC_USE_WHITENOISE

BASE_URL = Env("DOMAIN_NAME")
SECRET_KEY = Env("SECRET_KEY")

# Application definition

ADMIN_APPS = [
    "admin_interface",
    "colorfield",
    # "unfold",  # before django.contrib.admin
    # "unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.forms",  # optional, if special form elements are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    "django.contrib.admin",
]

DEFAULT_DJANGO_APPS: list[str] = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sitemaps",
]


THIRD_PARTY_APPS: list[str] = [
    "frontend_kit",
    "storages",
    "django_extensions",
    "constance",
    "django_structlog",
    "django_object_actions",  # https://github.com/crccheck/django-object-actions
    "solo",  # https://github.com/lazybird/django-solo
    # "rest_framework",
    # "drf_spectacular",
    # django-widget-tweaks
    # "widget_tweaks",
    # Django feather (Feather icons)
    # "django_feather",
    # Django HTMX
    # "django_htmx",
    # django-phonenumber-field
    # "phonenumber_field", Uncomment to enable
    # https://github.com/theatlantic/django-nested-admin
    # "nested_admin",
    # https://github.com/SmileyChris/easy-thumbnails
    # "easy_thumbnails",
    # https://github.com/pmclanahan/django-celery-email
    # "djcelery_email",
]

PROJECT_APPS: list[str] = [
    "app.apps.Config",
]

ALL_AUTH_APPS: list[str] = [
    # NOTE: Uncomment below lines to enable authentication
    # "allauth",
    # "allauth.account",
    # "allauth.socialaccount",
]

INSTALLED_APPS = [
    *ADMIN_APPS,
    *DEFAULT_DJANGO_APPS,
    *THIRD_PARTY_APPS,
    *PROJECT_APPS,
    *ALL_AUTH_APPS,
]

if DEBUG:
    INSTALLED_APPS += [
        "django_browser_reload",
    ]


MIDDLEWARE: list[str] = [
    # Logging:
    # "app.middleware.disable_client_side_caching_middleware", # Uncomment this line to disable client side caching # noqa
    # "django.middleware.cache.UpdateCacheMiddleware",  # This must be first on the list # noqa
    # "app.settings.components.logging.LoggingContextVarsMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    # Content Security Policy:
    "csp.middleware.CSPMiddleware",
    # Django:
    "django.middleware.security.SecurityMiddleware",
    # django-permissions-policy
    "django_permissions_policy.PermissionsPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Django HTTP Referrer Policy:
    "django_http_referrer_policy.middleware.ReferrerPolicyMiddleware",
    # Django HTMX
    "django_htmx.middleware.HtmxMiddleware",
    # "django.middleware.cache.FetchFromCacheMiddleware",  # This must be last
]

if STATIC_USE_WHITENOISE:
    MIDDLEWARE += [
        "whitenoise.middleware.WhiteNoiseMiddleware",
    ]


ROOT_URLCONF = "app.urls"

# Templates
# https://docs.djangoproject.com/en/3.2/ref/templates/api

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # Contains plain text templates, like `robots.txt`:
            BASE_DIR / "app" / "templates",
            DJFK_FRONTEND_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Default template context processors:
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
                # Django CSP
                "csp.context_processors.nonce",
                # Custom
                "app.context_processors.get_site_data",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

APPEND_SLASH = True


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_TZ = True

TIME_ZONE = "UTC"

LANGUAGES = (("en", _("English")),)

USE_I18N = False

USE_L10N = True

DATE_INPUT_FORMATS = ("%d-%m-%Y", "%Y-%m-%d")


# https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber-default-region
PHONENUMBER_DEFAULT_REGION = "US"  # Defaults to India


# Messages
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"
MESSAGE_TAGS = {
    messages.DEBUG: "gray",
    messages.INFO: "blue",
    messages.SUCCESS: "green",
    messages.WARNING: "yellow",
    messages.ERROR: "red",
}
