#!/bin/sh
set -e
set -o pipefail
docker-compose -f development.yml up -d
if [ $? -eq 0 ];
  then
    env poetry run python manage.py migrate
    env poetry run python manage.py runserver 0.0.0.0:8000
fi
