# Generated by Django 6.0 on 2026-08-07.

import django.utils.timezone
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("platform", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AdminImpersonationAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("started", "Started"), ("ended", "Ended")],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="impersonation_audit_events_as_actor",
                        to="platform.user",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="impersonation_audit_events_as_target",
                        to="platform.user",
                    ),
                ),
            ],
            options={"ordering": ("-occurred_at",)},
        ),
        migrations.AddIndex(
            model_name="adminimpersonationauditevent",
            index=models.Index(fields=["actor", "occurred_at"], name="platform_ad_actor_i_9c29a5_idx"),
        ),
        migrations.AddIndex(
            model_name="adminimpersonationauditevent",
            index=models.Index(fields=["target", "occurred_at"], name="platform_ad_target__b27310_idx"),
        ),
    ]
